# Generated by Django 4.1.3 on 2022-12-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='movie/static')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
